name: thegladscientist
favicon: null
layout_spectrum: 1
typography_spectrum: 0.09987
title: The Musings of a Glad Scientist
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f20'
    - '#1aacaf'
    - '#1d7274'
    - '#5f5e60'
    - '#9c4e83'
  brandStrength: 0.6875
  lightness: 0.25
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
